version: '3'

services:
  auth:
    build:
      context: ./auth
      args:
      - PUBLIC_URL=/
    image: gems/auth
    networks:
      - gems_net

  acl:
    build:
      context: ./acl
      args:
      - PUBLIC_URL=/acl
    image: gems/acl
    networks:
      - gems_net

  ems:
    build:
      context: ./ems
      args:
      - PUBLIC_URL=/ems
    image: gems/ems
    networks:
      - gems_net


  gateway:
    build:
      context: ./gateway
    image: gems/getway
    ports:
      - 3322:80
    networks:
      - gems_net
    depends_on:
      - auth
      - acl
      - ems

networks:
  gems_net: {}
